apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: kubeshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: rashadw/backend:latest
        ports:
        - containerPort: 8080
